-- MySQL Script generated by MySQL Workbench
-- Sun Nov  4 11:36:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema camagru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema camagru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camagru` DEFAULT CHARACTER SET utf8 ;
USE `camagru` ;

-- -----------------------------------------------------
-- Table `camagru`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`USERS` (
  `id_user` INT(10) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `confirm` ENUM('0', '1') NOT NULL,
  `recover` INT(10) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camagru`.`PHOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`PHOTOS` (
  `id_photo` INT(10) NOT NULL,
  `id_user` INT(10) NOT NULL,
  `nb_like` INT(11) NOT NULL DEFAULT 0,
  `date_creation` INT(10) NOT NULL,
  `location` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id_photo`),
  INDEX `fk_PHOTOS_USERS_idx` (`id_user` ASC),
  CONSTRAINT `fk_photos_id_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `camagru`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camagru`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`COMMENTS` (
  `id_comment` INT(10) NOT NULL,
  `id_user` INT(10) NOT NULL,
  `id_photo` INT(10) NOT NULL,
  `text` TEXT(500) NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comments_id_photo_idx` (`id_photo` ASC),
  INDEX `fk_comments_id_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_comments_id_photo`
    FOREIGN KEY (`id_photo`)
    REFERENCES `camagru`.`PHOTOS` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `camagru`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `camagru`.`USERS`
-- -----------------------------------------------------
START TRANSACTION;
USE `camagru`;
INSERT INTO `camagru`.`USERS` (`id_user`, `username`, `email`, `password`, `confirm`, `recover`) VALUES (1509400800, 'root', 'yanndarlet@gmail.com', 'eebcc3f3aabd1e79b0b49b8bdedc4e7a988d89da5904418015b68a58792c78f4927d77684238314d096222ed5498cd2c381f125ab052bc379c99c4b01b5c6f1f', '1', 1535282088);
INSERT INTO `camagru`.`USERS` (`id_user`, `username`, `email`, `password`, `confirm`, `recover`) VALUES (1509573600, 'ydarlet', 'ydarlet@student.42.fr', 'a830652e27c831248839ba1fafcbc1bc97b8d4a327c1adb218cbdcaa9b1a0e01a92b90c6edd0fdc550d2d5d24e5997062da3d8282a32be39ceabcf393c9388a3', '1', NULL);
INSERT INTO `camagru`.`USERS` (`id_user`, `username`, `email`, `password`, `confirm`, `recover`) VALUES (1520379899, 'jojolapin', 'yann.darlet@gmail.com', 'b5f977afffb5a26c8617c14513c3e8a690f3d5142d86033f16cfc9d4fa872ec03a8ee2b7a7cafc41eaae013ba6c0a8f924bdf1ebbd169cad69a88ae08dbc8373', '0', NULL);

COMMIT;

